import dotenv from "dotenv";
import { Pool } from "pg";
import { normalizeDatabaseUrl } from "../src/db/connectionString.js";

const DEFAULT_SONG_TAG_DEFINITIONS = [
  { slug: "espanol", label: "Español" },
  { slug: "ingles", label: "Inglés" },
  { slug: "instrumental", label: "Instrumental" },
  { slug: "musica_clasica", label: "Música clásica" },
  { slug: "tropical", label: "Tropical" },
  { slug: "dance", label: "Dance" },
  { slug: "rock", label: "Rock" },
  { slug: "pop", label: "Pop" },
];

dotenv.config({ path: ".env.local", quiet: true });

const databaseUrl = normalizeDatabaseUrl(process.env.DATABASE_URL ?? "");

if (!databaseUrl) {
  throw new Error("DATABASE_URL is missing.");
}

const pool = new Pool({ connectionString: databaseUrl });

const statements = [
  `
  create table if not exists songs (
    id integer generated by default as identity primary key,
    artist text not null,
    title text not null,
    year integer,
    youtube_url text not null,
    isspanish boolean not null default false
  );
  `,
  `
  alter table songs
  add column if not exists youtube_status text;
  `,
  `
  alter table songs
  add column if not exists song_attributes text[] not null default '{}'::text[];
  `,
  `
  update songs
  set song_attributes = case
    when coalesce(isspanish, false) then array['espanol']::text[]
    else '{}'::text[]
  end
  where song_attributes is null or array_length(song_attributes, 1) is null;
  `,
  `
  create index if not exists songs_song_attributes_gin_idx
  on songs using gin (song_attributes);
  `,
  `
  alter table songs
  add column if not exists youtube_validation_message text;
  `,
  `
  alter table songs
  add column if not exists youtube_validation_code integer;
  `,
  `
  alter table songs
  add column if not exists youtube_validated_at timestamptz;
  `,
  `
  drop index if exists songs_youtube_url_unique;
  `,
  `
  create unique index if not exists songs_public_youtube_url_unique
  on songs (youtube_url)
  where scope = 'public';
  `,
  `
  create unique index if not exists songs_personal_owner_youtube_url_unique
  on songs (owner_user_id, youtube_url)
  where scope = 'personal';
  `,
  `
  create table if not exists admin_users (
    id integer generated by default as identity primary key,
    email text not null unique,
    password_hash text not null,
    role text not null,
    display_name text,
    avatar_url text,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  );
  `,
  `
  create table if not exists song_tags (
    id integer generated by default as identity primary key,
    slug text not null unique,
    label text not null,
    active boolean not null default true,
    created_by integer references admin_users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  );
  `,
  `
  alter table admin_users
  add column if not exists display_name text;
  `,
  `
  alter table admin_users
  add column if not exists avatar_url text;
  `,
  `
  alter table songs
  add column if not exists catalog_status text not null default 'pending';
  `,
  `
  alter table songs
  add column if not exists scope text not null default 'public';
  `,
  `
  alter table songs
  add column if not exists owner_user_id integer references admin_users(id) on delete cascade;
  `,
  `
  alter table songs
  add column if not exists source_song_id integer;
  `,
  `
  alter table songs
  add column if not exists created_by integer references admin_users(id) on delete set null;
  `,
  `
  alter table songs
  add column if not exists approved_by integer references admin_users(id) on delete set null;
  `,
  `
  alter table songs
  add column if not exists approved_at timestamptz;
  `,
  `
  alter table songs
  add column if not exists created_at timestamptz not null default now();
  `,
  `
  alter table songs
  add column if not exists updated_at timestamptz not null default now();
  `,
  `
  create table if not exists playlists (
    id integer generated by default as identity primary key,
    name text not null,
    description text,
    active boolean not null default true,
    scope text not null default 'public',
    owner_user_id integer references admin_users(id) on delete cascade,
    created_by integer references admin_users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  );
  `,
  `
  alter table playlists
  add column if not exists scope text not null default 'public';
  `,
  `
  alter table playlists
  add column if not exists owner_user_id integer references admin_users(id) on delete cascade;
  `,
  `
  alter table playlists drop constraint if exists playlists_name_unique;
  `,
  `
  drop index if exists playlists_name_unique;
  `,
  `
  create unique index if not exists playlists_public_name_unique
  on playlists (name)
  where scope = 'public';
  `,
  `
  create unique index if not exists playlists_personal_owner_name_unique
  on playlists (owner_user_id, name)
  where scope = 'personal';
  `,
  `
  create table if not exists playlist_songs (
    id integer generated by default as identity primary key,
    playlist_id integer not null references playlists(id) on delete cascade,
    song_id integer not null references songs(id) on delete cascade,
    position integer not null default 0,
    added_by integer references admin_users(id) on delete set null,
    created_at timestamptz not null default now()
  );
  `,
  `
  alter table playlists
  add column if not exists created_by integer references admin_users(id) on delete set null;
  `,
  `
  alter table playlist_songs
  add column if not exists added_by integer references admin_users(id) on delete set null;
  `,
  `
  alter table playlist_songs
  add column if not exists created_at timestamptz not null default now();
  `,
  `
  create unique index if not exists playlist_songs_playlist_song_unique
  on playlist_songs (playlist_id, song_id);
  `,
  `
  create table if not exists game_sessions (
    id integer generated by default as identity primary key,
    mode text not null default 'auto',
    year_min integer,
    year_max integer,
    only_spanish boolean not null default false,
    selected_song_attributes text[] not null default '{}'::text[],
    tag_match_mode text not null default 'any',
    timer_enabled boolean not null default false,
    created_at timestamptz not null default now()
  );
  `,
  `
  alter table game_sessions
  add column if not exists selected_song_attributes text[] not null default '{}'::text[];
  `,
  `
  alter table game_sessions
  add column if not exists tag_match_mode text not null default 'any';
  `,
  `
  update game_sessions
  set selected_song_attributes = case
    when coalesce(only_spanish, false) then array['espanol']::text[]
    else '{}'::text[]
  end
  where selected_song_attributes is null
    or array_length(selected_song_attributes, 1) is null;
  `,
  `
  alter table game_sessions
  add column if not exists playlist_id integer;
  `,
  `
  alter table game_sessions
  add column if not exists playlist_name text;
  `,
  `
  create index if not exists game_sessions_created_at_idx
  on game_sessions (created_at);
  `,
];

async function main() {
  const client = await pool.connect();
  try {
    for (const stmt of statements) {
      await client.query(stmt);
    }
    for (const tag of DEFAULT_SONG_TAG_DEFINITIONS) {
      await client.query(
        `
        insert into song_tags (slug, label, active, updated_at)
        values ($1, $2, true, now())
        on conflict (slug) do update
        set label = excluded.label,
            active = true,
            updated_at = now()
        `,
        [tag.slug, tag.label]
      );
    }
    console.log("Neon schema ready.");
  } finally {
    client.release();
    await pool.end();
  }
}

main().catch((err) => {
  console.error("Failed to setup Neon:", err);
  process.exit(1);
});
