import dotenv from "dotenv";
import { Pool } from "pg";

dotenv.config({ path: ".env.local", quiet: true });

const databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error("DATABASE_URL is missing.");
}

const pool = new Pool({ connectionString: databaseUrl });

const statements = [
  `
  create table if not exists songs (
    id integer generated by default as identity primary key,
    artist text not null,
    title text not null,
    year integer,
    youtube_url text not null,
    isspanish boolean not null default false
  );
  `,
  `
  create unique index if not exists songs_youtube_url_unique
  on songs (youtube_url);
  `,
  `
  create table if not exists admin_users (
    id integer generated by default as identity primary key,
    email text not null unique,
    password_hash text not null,
    role text not null,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  );
  `,
];

async function main() {
  const client = await pool.connect();
  try {
    for (const stmt of statements) {
      await client.query(stmt);
    }
    console.log("Neon schema ready.");
  } finally {
    client.release();
    await pool.end();
  }
}

main().catch((err) => {
  console.error("Failed to setup Neon:", err);
  process.exit(1);
});
